### ISSUE TITLE
[BUG] WebAuthn failed on iOS 14.5 or above

### ISSUE THREAD

**Issue by dingwen07** [anonaddy/anonaddy#169]
After trying to login in in iOS 14.5 or above, the error message "The operation either timed out or was not allowed." is displayed.

WebAuthn works for other sites.

**Comment by willbrowningme** [comment]
Is anyone else able to verify this issue? I do not have access to an iPhone to attempt to replicate this myself.

**Comment by ccorneli** [comment]
Works for me, but I'm not clear how it was originally tried.
I'm using iOS 14.6, opened safari on my iPhone.. (which happened to use a "private" window) and logged in fine to anonAddy.com.  Note: I also have 2FA setup so needed to give the passcode as well.  

If it is still an issue for OP, it would help to provide more details on what you were doing to reproduce it.

**Comment by zmilonas** [comment]
It's also failing in Safari 14.1.1, macOS 11.4 so I would broaden the scope of the bug to say "WebAuthn doesn't work in Safari - macOS or iOS"

The exact error I see is 
```
User gesture is not detected. To use the WebAuthn API, call 'navigator.credentials.create' within user activated events
```

Pointing to this line in the JavaScript:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/25948390/127774509-6e89c5a8-6f83-4449-891e-cf98133667d4.png">

This seems to be the related documentation from Yubico themselves:
https://support.yubico.com/hc/en-us/articles/360022004600-No-reaction-when-using-WebAuthn-on-macOS-iOS-and-iPadOS

> Due to recent changes to Apple devices this may occur when a WebAuthn request is initiated without a user activated event including events such as, 'click', 'touchend', 'doubleclick', or 'keydown' events.

So it seems like the needed code change would be to add a button like "Proceed to 2FA" that would trigger the WebAuthn API.

I can later look into the code and maybe prepare a PR for that.

**Comment by willbrowningme** [comment]
I'm using this package for WebAuthn - https://github.com/asbiin/laravel-webauthn

I've followed the example as set out by the package author.

Thanks @zmilonas, so this would need to be on the authenticate file here? - https://github.com/anonaddy/anonaddy/blob/master/resources/views/vendor/webauthn/authenticate.blade.php (when logging in).

**Comment by zmilonas** [comment]
Yes I think just any interaction button in the file you posted would suffice

**Comment by willbrowningme** [comment]
@zmilonas Okay, I've just pushed an update that adds a new "Authenticate" button that can be clicked so the WebAuthn request is initiated by a user activated event. Please give it a go and let me know if it works.

**Comment by dingwen07** [comment]
> @zmilonas Okay, I've just pushed an update that adds a new "Authenticate" button that can be clicked so the WebAuthn request is initiated by a user activated event. Please give it a go and let me know if it works.

I tested it on iOS and WebAuthn worked after clicking the "Authenticate" button, although the initial error message still appeared on authentication page load.

**Comment by willbrowningme** [comment]
@dingwen07 Thanks, the javascript does still currently try to issue the WebAuthn request automatically on page load which will be why you still saw the error. I just added the button to allow the user to intitiate the request manually too.

**Comment by zmilonas** [comment]
@willbrowningme it works for me!

Maybe at some later time the banner can also be hidden by right now I'm really happy I don't have to switch a browser to login

Thank you for quickly fixing this.

**Comment by dingwen07** [comment]
> @dingwen07 Thanks, the javascript does still currently try to issue the WebAuthn request automatically on page load which will be why you still saw the error. I just added the button to allow the user to intitiate the request manually too.

Is that possible to change the logic to let the error message doesn't appear? Like ignoring the error of the authentication request initiated on page load.

**Comment by willbrowningme** [comment]
I've just added a quick check to skip the automatic webauthn request if the browser is Safari, please try again and let me know if the error has gone.

**Comment by dingwen07** [comment]
> I've just added a quick check to skip the automatic webauthn request if the browser is Safari, please try again and let me know if the error has gone.

The error message is gone, thank you!
