### ISSUE TITLE
Remove Email Banner in replies

### ISSUE THREAD

**Issue by HeikoBornholdt** [anonaddy/anonaddy#253]
It would be great if the Email Banner could be automatically removed in replies.

This would prevent the AnonAddy URL and (private) description from being disclosed to the recipient.

**Comment by DNCD** [comment]
you can remove the Email Banner  for every email you receive by going into the settings, look for  "Update Email Banner Location, and selecting OFF."

**Comment by Koellewe** [comment]
@heikobornholdt the feature has already been implemented. Please close this issue.

**Comment by heikobornholdt** [comment]
Hey @Koellewe  👋,
Do you mean the feature mentioned by @DNCD ?
That's not actually the feature I suggested, as it will disable the banner at all.

My feature suggestion prevents the email banner information from being disclosed to the recipient when replying to an email.

**Comment by willbrowningme** [comment]
This should be working now, please give it a try and let me know if everything is as expected. (It will only remove the banner from newly forwarded messages starting from now).

**Comment by nielscil** [comment]
The plain text works good, but when using html and outlook desktop client the comments are being removed when replying:


### Incoming
```
<table style="width:100%;">
	<tbody>
		<!--banner-info-->
		<tr>
			<td>
				<div
					style="margin:0px auto;max-width:896px;padding:10px 20px;background-color:#f5f7fa;text-align:center;line-height:1.5;font-size:12px;width:100%;border-left: 3px solid #19216c;font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';color:#323f4b;"
				>
					This email was sent to <span style="font-weight:500;color:#19216c;">test@test.com</span> (test) from <span style="font-weight:500;color:#19216c;">somebody@domain.com</span><br />
					Click
					<a
						href="<link>"
						style="color:#2d3a8c;text-decoration:underline;"
						target="_blank"
						rel="noreferrer noopener nofollow"
					>
						here
					</a>
					to deactivate this alias
				</div>
			</td>
		</tr>
		<!--banner-info-->

		....
		
	</tbody>
</table>
```

### Outgoing

```
<html
	xmlns:v="urn:schemas-microsoft-com:vml"
	xmlns:o="urn:schemas-microsoft-com:office:office"
	xmlns:w="urn:schemas-microsoft-com:office:word"
	xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
	xmlns="http://www.w3.org/TR/REC-html40">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="Generator" content="Microsoft Word 15 (filtered medium)" />
		<style>
			...
		</style>
		<!--[if gte mso 9]>
			<xml>
				<o:shapedefaults v:ext="edit" spidmax="1026" />
			</xml>
		<![endif]-->
		<!--[if gte mso 9]>
			<xml>
				<o:shapelayout v:ext="edit">
					<o:idmap v:ext="edit" data="1" />
				</o:shapelayout>
			</xml>
		<![endif]-->
	</head>
	<body lang="NL" link="blue" vlink="purple" style="word-wrap:break-word">
		<div class="WordSection1">
			
			...
			
			<table class="MsoNormalTable" border="0" cellpadding="0" width="100%" style="width:100.0%">
				<tr>
					<td style="padding:.75pt .75pt .75pt .75pt">
						<div style="border:none;border-left:solid #19216C 2.25pt;padding:0cm 0cm 0cm 15.0pt">
							<p class="MsoNormal" align="center" style="text-align:center;background:#F5F7FA">
								<span style='font-size:9.0pt;font-family:"Segoe UI",sans-serif;color:#323F4B'>This email was sent to </span>
								<span style='font-size:9.0pt;font-family:"Segoe UI",sans-serif;color:#19216C'><a href="mailto:test@test.com">test@test.com</a></span>
								<span style='font-size:9.0pt;font-family:"Segoe UI",sans-serif;color:#323F4B'> (test) from </span>
								<span style='font-size:9.0pt;font-family:"Segoe UI",sans-serif;color:#19216C'><a href="somebody@domain.com">somebody@domain.com</a></span>
								<span style='font-size:9.0pt;font-family:"Segoe UI",sans-serif;color:#323F4B'>
									<br />
									Click
									<a href="<link>" target="_blank">
										<span style="color:#2D3A8C">here</span>
									</a>
									to deactivate this alias <o:p></o:p>
								</span>
							</p>
						</div>
					</td>
				</tr>
				
				...
				
			</table>
			<p class="MsoNormal">
				<span style='font-family:"Times New Roman",serif'><o:p>&nbsp;</o:p></span>
			</p>
		</div>
	</body>
</html>
```

**Comment by willbrowningme** [comment]
@nielscil have you confirmed that this means the banner is not successfully removed if sending from the Outlook desktop client? I have no idea why they would choose to remove HTML comments.

**Comment by nielscil** [comment]
Yeah, it doesn't remove the banner.

**Comment by willbrowningme** [comment]
Okay, thanks for the update, that is obviously a problem, I'll have to change the regex matches to something else that cannot be removed.

**Comment by willbrowningme** [comment]
I can confirm that this was also affecting the Outlook mobile app. I've just pushed a fix for it now, please could you try it with a newly forwarded message?

**Comment by nielscil** [comment]
Sure, but I don't see the fix in the commits of the repo yet.

**Comment by willbrowningme** [comment]
I just pushed the commit to GitHub now - https://github.com/anonaddy/anonaddy/commit/fa5a7a87d73a6e2de9736744477365537edc2008

**Comment by nielscil** [comment]
On mobile outlook it works indeed. From desktop it still does not. Output message does not contain the id to match anymore:

````
<tr style="mso-yfti-irow:0;mso-yfti-firstrow:yes">
	<td style="padding:.75pt .75pt .75pt .75pt">
		<div style="border:none;border-left:solid #19216C 2.25pt;padding:0cm 0cm 0cm 15.0pt;overflow-wrap:break-word">
			<p class="MsoNormal" align="center" style="text-align:center;background:#F5F7FA">
				<span style='font-size:9.0pt;font-family:"Segoe UI",sans-serif;color:#323F4B'>This email was sent to </span>
				<span style='font-size:9.0pt;font-family:"Segoe UI",sans-serif;color:#19216C'><a href="mailto:test@test.com">test@test.com</a></span>
				<span style='font-size:9.0pt;font-family:"Segoe UI",sans-serif;color:#323F4B'> (test) from </span>
				<span style='font-size:9.0pt;font-family:"Segoe UI",sans-serif;color:#19216C'><a href="mailto:somebody@domain.com">somebody@domain.com</a></span>
				<span style='font-size:9.0pt;font-family:"Segoe UI",sans-serif;color:#323F4B'>
					<br />
					Click
					<a href="<link>" target="_blank">
						<span style="color:#2D3A8C">here</span>
					</a>
					to deactivate this alias <o:p></o:p>
				</span>
			</p>
		</div>
	</td>
</tr>
````

**Comment by nielscil** [comment]
Yeah, it was. I can confirm that when I recieved the message the id was there, but when replying to it, it was removed.

**Comment by willbrowningme** [comment]
Hmm, it is proving very difficult to write a fool-proof regular expression given all the alterations that seem to be happening by different email clients.

**Comment by willbrowningme** [comment]
Okay, I think I've found a solution, please could you try again now.

**Comment by willbrowningme** [comment]
Just pushed the commit live now - https://github.com/anonaddy/anonaddy/commit/24b828667527fcf2c47e0fd46610c70127a20f69

**Comment by nielscil** [comment]
I've tested the latest fix and it seems to be working now on Outlook desktop and in the outlook android app. Tnx!

**Comment by alexaka1** [comment]
Does this still work? 
Replying to an email from Protonmail (both web and android), keeps the banner in the "Show original" menu in Gmail.
When opening the email in gmail (web), the history has no visible trace of the banner. But clicking the "Show original" menu, and ctrl+f deactivate, it's still there in the body.

Mobile:
```
...
Content-Type: multipart/mixed; boundary=h6EKM32P

--h6EKM32P
Content-Type: multipart/alternative; boundary=8AWGP0ZV

--8AWGP0ZV
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Some reply mobile

-------- Original Message --------
On 9 Feb 2023, 13:27, redacted 'redacted at gmail.com' wrote:

> This email was sent to redacted@redacted from redacted@gmail=
.com
> Click [here](https://app.anonaddy.com/deactivate/redacted?signature=redacted) to deactivate this alias
--8AWGP0ZV
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Some reply mobile<br><br><br><br><br><br><br>-------- Original Message ----=
----<br>On 9 Feb 2023, 13:27, redacted 'redacted at gmail.com' =
< redacted+redacted=3Dgmail.com@redacted> wrote:<blockquote cl=
ass=3D"protonmail_quote"><br><table style=3D"width:100%;">
        <tbody>
                                                    <tr>
                <td style=3D"padding:10px 0;width:100%;">
                    <div dir=3D"auto"></div>

                </td>
            </tr>
                    </tbody>
    </table>
</div>
--8AWGP0ZV--
--h6EKM32P
Content-Type: application/pdf; name="redacted"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; name="redacted"; filename="redacted"


--h6EKM32P--
```
Web:
```
...
Content-Type: multipart/alternative; boundary=ZbSoiIHK

--ZbSoiIHK
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

some reply

------- Original Message -------
On Wednesday, February 8th, 2023 at 17:08, redacted 'redacted a=
t gmail.com' <redacted+redacted=3Dgmail.com@redacted> wrote:

> This email was sent to redacted@redacted from redacted@gmail=
.com
> Click [here](https://app.anonaddy.com/deactivate/redacted?signature=redacted) to deactivate this alias
--ZbSoiIHK
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<div style=3D"font-family: Arial, sans-serif; font-size: 14px;">some reply<=
/div>
<div class=3D"protonmail_signature_block protonmail_signature_block-empty" =
style=3D"font-family: Arial, sans-serif; font-size: 14px;">
    <div class=3D"protonmail_signature_block-user protonmail_signature_bloc=
k-empty">
       =20
            </div>
   =20
            <div class=3D"protonmail_signature_block-proton protonmail_sign=
ature_block-empty">
       =20
            </div>
</div>
<div style=3D"font-family: Arial, sans-serif; font-size: 14px;"><br></div><=
div class=3D"protonmail_quote">
        ------- Original Message -------<br>
        On Wednesday, February 8th, 2023 at 17:08, redacted 'redacted at gmail.com' &lt;redacted+redacted=3Dgmail.com@redacted&gt; wrote:<br><br>
        <blockquote class=3D"protonmail_quote" type=3D"cite">
            <table style=3D"width:100%;">
        <tbody>
                                                    <tr>
                <td style=3D"padding:10px 0;width:100%;">
                    <div dir=3D"ltr"><br></div>

                </td>
            </tr>
                    </tbody>
    </table>

        </blockquote><br>
    </div>
--ZbSoiIHK--
```

**Comment by willbrowningme** [comment]
@alexaka1 could you send me an email and let me know one of your aliases so I can test this when you reply?
